# Generated by Django 5.2.1 on 2026-10-09 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='UtilityRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electric_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('water_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_date', models.DateField()),
            ],
            options={
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('room_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('electric_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('water_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('chua_thanh_toan', 'Chưa thanh toán'), ('da_thanh_toan', 'Đã thanh toán'), ('qua_han', 'Quá hạn')], default='chua_thanh_toan', max_length=20)),
                ('due_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='rooms.contract')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_date', models.DateField(auto_now_add=True)),
                ('method', models.CharField(choices=[('tien_mat', 'Tiền mặt'), ('chuyen_khoan', 'Chuyển khoản')], default='tien_mat', max_length=20)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='UtilityReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('old_electric', models.PositiveIntegerField()),
                ('new_electric', models.PositiveIntegerField()),
                ('old_water', models.PositiveIntegerField()),
                ('new_water', models.PositiveIntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utility_readings', to='rooms.room')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='utility_reading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='billing.utilityreading'),
        ),
        migrations.CreateModel(
            name='InvoiceService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_services', to='billing.invoice')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.service')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('invoice', 'service'), name='unique_invoice_service')],
            },
        ),
        migrations.AddConstraint(
            model_name='utilityreading',
            constraint=models.UniqueConstraint(fields=('room', 'month', 'year'), name='unique_room_month_year_reading'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('contract', 'month', 'year'), name='unique_contract_month_year_invoice'),
        ),
    ]
