# Generated by Django 5.2.1 on 2026-10-09 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_occupants', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('trong', 'Trống'), ('dang_thue', 'Đang thuê'), ('bao_tri', 'Bảo trì')], default='trong', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('hieu_luc', 'Hiệu lực'), ('ket_thuc', 'Kết thúc')], default='hieu_luc', max_length=20)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='rooms.room')),
            ],
        ),
        migrations.CreateModel(
            name='ContractTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_representative', models.BooleanField(default=False)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_tenants', to='rooms.contract')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_tenants', to='accounts.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('contract', 'tenant'), name='unique_contract_tenant')],
            },
        ),
    ]
